version: '3'
services:
  mysql_db:
    container_name: mysql_db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./database:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: $ROOTPASSWORD
      MYSQL_DATABASE: $DATABASE
      MYSQL_USER: $USERNAME
      MYSQL_PASSWORD: $PASSWORD
    ports:
      - 3306:3306