version: '3'

services:
  app:
    container_name: app
    build: ./app/
    ports:
      - 8000:8000
    volumes:
      - ./app/src:/usr/src/app/src
    environment:
      PORT: $PORT
      HOST: $HOST
      USERNAME: $USERNAME
      PASSWORD: $PASSWORD
      DATABASE: $DATABASE
      SESSIONSECRET: $SESSIONSECRET
    depends_on:
      - mysql_db

  mysql_db:
    container_name: mysql_db
    # image: mysql:5.7
    build: ./database/
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./database/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: $ROOTPASSWORD
      MYSQL_DATABASE: $DATABASE
      MYSQL_USER: $USERNAME
      MYSQL_PASSWORD: $PASSWORD
    ports:
      - 3306:3306